Repository SimpleREST/stub-framework, pull requests merged in 2023-11, with the labels that each got.

#14 Develop
  composer.json
  src/Console/Base/Command.php
  src/Console/Base/Output.php
  src/Console/Commands/AboutCommand.php
  src/Console/Commands/Config/ConfigListCommand.php
  src/Console/Commands/CountdownCommand.php
  src/Console/Commands/HelpCommand.php
  src/Console/Commands/ListCommand.php
  src/Console/Commands/Make/MakeNewCustomStubCommand.php
  src/Console/Commands/ResetCommand.php
  src/Contracts/Console/Commands.php
  src/Contracts/Console/Output.php
  src/Contracts/Main/ContainingResources.php
  src/Http/View/Stub.php
  src/Main/Application.php
  src/Main/Assets/BaseDefaultStubResource.php
  src/Main/Console/Kernel.php
  src/Main/Http/Kernel.php
Labels: bug, enhancement

#15 Develop
  README.md
  src/Contracts/Main/Application.php
  src/Main/Application.php
  src/Main/Console/Kernel.php
  src/Main/Http/Kernel.php
Labels: bug, documentation, enhancement

#16 Develop
  src/Console/Base/Command.php
  src/Console/Base/Input.php
  src/Console/Base/Output.php
  src/Console/Base/Terminal.php
  src/Contracts/Main/Application.php
  src/Contracts/Main/UserEditable.php
  src/Http/View/Stub.php
  src/Main/Application.php
  src/Main/Assets/BaseDefaultStubResource.php
  src/Main/Http/Kernel.php
  src/Main/MainConfig.php
Labels: enhancement

#17 Develop
  src/Contracts/Config/ReadableConfiguration.php
  src/Contracts/Main/Application.php
  src/Http/View/Stub.php
  src/Main/Application.php
  src/Main/Http/Kernel.php
  src/Main/MainConfig.php
Labels: enhancement
